# Generated by Django 4.0.4 on 2022-05-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_address_datetime_created_address_datetime_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('ran_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
